---
# Prompt for the first target.
#
# optional vars:
#  label: A label for the target, used when prompting.
#  first_target_dns: the dns name of the first target.
#  khan_dns: the dns name of the first target.
#  bastion_eip: external IP of a bastion host, which is (optionally) used as a bounce host, to access the target.
# sets:
#  first_target_dns (if not supplied).
#
# creates:
#  host group 'first_target_host'

- name: ensure label is set
  set_fact: label='the first target host'
  when: label is undefined

- name: Select target
  pause:
    prompt: 'what is the DNS name of {{ label }}?'
  register: first_target
  when: first_target_dns is not defined and khan_dns is not defined

- name: set fact from prompt
  set_fact:
    first_target_dns: '{{ first_target.user_input }}'
  when: first_target_dns is not defined and khan_dns is not defined

- name: set fact from khan_dns
  set_fact:
    first_target_dns: '{{ khan_dns }}'
  when: khan_dns is defined

- name: add first target (behind bastion host)
  add_host:
    name: '{{ first_target_dns }}'
    groups: first_target_host
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@{{ bastion_eip }}" -o StrictHostKeyChecking=no -o serveraliveinterval=60 -l ubuntu'
  when: bastion_eip is defined

- name: add first_target
  add_host:
    name: '{{ first_target_dns }}'
    groups: first_target_host
    ansible_ssh_common_args: '-o serveraliveinterval=60'
  when: bastion_eip is not defined
