github_repos:
  - 'wireapp/wire-server-deploy.git'
  - 'wireapp/wire-server-deploy-networkless'
  - 'wireapp/ansible-cassandra.git'
  - 'wireapp/ansible-minio.git'
  - 'wireapp/ansible-restund.git'
  - 'wireapp/ansible-tinc.git'
  - 'wireapp/ansible-ntp-verify.git'
  - 'elastic/ansible-elasticsearch.git'
  - 'ANXS/hostname.git'
  - 'ANXS/apt.git'
  - 'geerlingguy/ansible-role-java.git'
  - 'geerlingguy/ansible-role-ntp.git'
  - 'githubixx/ansible-role-kubectl.git'
  - 'andrewrothstein/ansible-kubernetes-helm.git'
  - 'cchurch/ansible-role-admin-users.git'
  - 'kubernetes-sigs/kubespray.git'
  - 'nickhammond/ansible-logrotate.git'
