---
- name: ensure offline_delivery_dir is set
  set_fact: offline_delivery_dir='/home/ubuntu/offline_delivery/'
  when: offline_delivery_dir is undefined

- name: ensure fake_domain is given.
  fail:
    msg: 'fake_domain must be set'
  when: fake_domain is undefined

- name: ensure admin_ip is given.
  fail:
    msg: 'admin_ip must be set'
  when: admin_ip is undefined

- name: ensure dnsmasq directory exists
  file:
    path: '{{ offline_delivery_dir }}/dnsmasq/dnsmasq.d/'
    state: directory
  become: yes

- name: add DNS entry for admin
  copy:
    content: |
      address=/ip-{{ admin_ip | replace('.','-')}}.{{ fake_domain }}/{{ admin_ip }}
    dest: '{{ offline_delivery_dir }}/dnsmasq/dnsmasq.d/admin'

- name: restart DNSMASQ
  systemd:
    name: dnsmasq
    state: restarted
    daemon_reload: yes
  become: yes


