- name: Check dependencies
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: Verify Ansible version meets this playbook's requirements
      include: tasks/version_check.yml
      vars:
        ansible_min_version: 2.7.0
        ansible_max_version: 2.8.0
      tags: always

- name: copy hosts.ini.adminhost to the adminhost
  hosts: admin
  gather_facts: no
  tasks:
    - copy:
        src: hosts.ini.adminhost
        dest: /home/ubuntu/hosts.ini