- name: Check dependencies
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: Verify Ansible version meets this playbook's requirements
      include: tasks/version_check.yml
      vars:
        ansible_min_version: 2.7.0
        ansible_max_version: 2.8.0
      tags: always

- name: Prepare admin host to run ansible
  hosts: admin
  gather_facts: no
  become: no
  tasks:
    - name: install apt dependencies
      become: yes
      apt:
        pkg:
        - python2.7
        - python-pip
    - name: include our definitions of the helm repo to use.
      include_vars: 'helm_repo.yml'
      when: helm_repo is undefined
    - name: grab wire-server-deploy
      git:
        repo: 'https://github.com/wireapp/wire-server-deploy.git'
        dest: '/home/ubuntu/wire-server-deploy'
        version: 'chart/wire-server-{{helm_repo.version}}'
    - name: create SSH key for admin host
      command: 'ssh-keygen -t rsa -f /home/ubuntu/.ssh/id_rsa -N ""'
      args:
        creates: /home/ubuntu/.ssh/id_rsa.pub
    - name: read admin rsa key
      command: 'cat /home/ubuntu/.ssh/id_rsa.pub'
      register: id_rsa
      tags: deploy_ssh_key

- name: Prepare managed hosts to accept SSH connections from admin
  hosts: kube-node, elasticsearch, cassandra, minio
  gather_facts: no
  become: no
  tasks:
     - name: add admin host rsa ssh key
       authorized_key:
         user: ubuntu
         state: present
         key: '{{ hostvars[groups["admin"][0]]["id_rsa"]["stdout"] }}'
       tags: deploy_ssh_key

