- name: Check dependencies
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: Verify Ansible version meets this playbook's requirements
      include: tasks/version_check.yml
      vars:
        ansible_min_version: 2.7.0
        ansible_max_version: 2.8.0
      tags: always

- name: Prepare admin host to run ansible
  hosts: admin
  gather_facts: no
  become: no
  tasks:
    - name: install apt dependencies
      become: yes
      apt:
        pkg:
        - python2.7
        - python-pip
    - name: grab get poetry script
      get_url:
        url: 'https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py'
        dest: '/home/ubuntu/get-poetry.py'
    - name: install poetry
      command: 'python2.7 /home/ubuntu/get-poetry.py --yes'
    - name: add python symlink to poetry
      file:
        dest: '$HOME/.poetry/bin/python'
        src: '/usr/bin/python2.7'
        state: link
    - name: reset ssh connection, so that we have the poetry environment loaded.
      meta: reset_connection
    - name: grab wire-server-deploy
      git:
        repo: 'https://github.com/wireapp/wire-server-deploy.git'
        dest: '/home/ubuntu/wire-server-deploy'
    - name: install wire-server-deploy dependencies with poetry
      shell: 'export PATH=$PATH:/home/ubuntu/.poetry/bin/ && poetry install'
      args:
        chdir: '/home/ubuntu/wire-server-deploy/ansible/'
      environment:
        CURL_CA_BUNDLE: '/etc/ssl/certs/ca-certificates.crt'
    - name: run make download
      shell: 'export PATH=$PATH:/home/ubuntu/.poetry/bin/ && make download'
      args:
        chdir: '/home/ubuntu/wire-server-deploy/ansible/'
      environment:
        CURL_CA_BUNDLE: '/etc/ssl/certs/ca-certificates.crt'
    - name: create SSH key for admin host
      command: 'ssh-keygen -t rsa -f /home/ubuntu/.ssh/id_rsa -N ""'
      args:
        creates: /home/ubuntu/.ssh/id_rsa.pub
    - name: read admin rsa key
      command: 'cat /home/ubuntu/.ssh/id_rsa.pub'
      register: id_rsa
      tags: deploy_ssh_key

- name: Prepare managed hosts to accept SSH connections from admin
  hosts: kube-node, elasticsearch, cassandra, minio
  gather_facts: no
  become: no
  tasks:
     - name: add admin host rsa ssh key
       authorized_key:
         user: ubuntu
         state: present
         key: '{{ hostvars[groups["admin"][0]]["id_rsa"]["stdout"] }}'
       tags: deploy_ssh_key

