---
- name: ensure offline_content_dir is set
  set_fact: offline_content_dir='/home/ubuntu/offline_content/'
  when: offline_content_dir is undefined

- name: ensure offline_delivery_dir is set
  set_fact: offline_delivery_dir='/home/ubuntu/offline_delivery/'
  when: offline_delivery_dir is undefined

- name: change permissions on debian repo, so it can be updated
  file:
    path: '{{ offline_content_dir }}/apt_repository'
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu
  become: yes
